### ISSUE TITLE
EXT trigger

### ISSUE THREAD

**Issue by mlukasek** [gusmanb/logicanalyzer#103]
Hello,

can I use the EXT pins as a trigger? It is connected to to the external connector, but I cannot find any software setting for the EXT trigger.

Kind regards

Martin

**Comment by gusmanb** [comment]
Hi.

The EXT pins are used to trigger external devices like an oscilloscope, whenever you use a complex or fast trigger (the pattern ones) the pin will go high when the trigger condition is detected.

More info [here](https://github.com/gusmanb/logicanalyzer/tree/master?tab=readme-ov-file#update-27112022---small-changes-great-value)

**Comment by mlukasek** [comment]
Oh, I see, thank you very much.
