### ISSUE TITLE
Multidevice with Network issue

### ISSUE THREAD

**Issue by IntergalacticMicrosystems** [gusmanb/logicanalyzer#104]
Having trouble with Multidevice and multiple Network slaves.
Looks like the connStr is off by one -
MultiConnectDialog.axaml.cs line 61
changing it to `connStr = tbs[buc+1].Text;` fixes it for me.

Super useful project - thank you!

**Comment by gusmanb** [comment]
Thanks for the report.
I have corrected it in the code and will be fixed in the next release.
