### ISSUE TITLE
How to stop capturing?

### ISSUE THREAD

**Issue by superyawei** [gusmanb/logicanalyzer#11]
Hi, brother
When I am capturing, I want to stop capturing; But I don't know how to stop scanning, only power off and restart.
Adding start and stop buttons to the software is a good choice.

**Comment by gusmanb** [comment]
Hi.

Thanks for the suggestion.

Right now there is no way to stop the capture becausue when I was developing the device I had some problems reading from the USB while the capture was running at full speed, so USB comms are not checked when the capture is running. I think the bus matrix is so saturated that it makes the RP2040 to crash.

In any case I will check it again and if I see that it works without causing problems will add the function to stop the capture.

Cheers.

**Comment by gusmanb** [comment]
Functionality to stop a running capture is under testing, probably next week will be published.

**Comment by superyawei** [comment]
very much looking forward to

**Comment by gusmanb** [comment]
Implemented in [release 2.0.1.0 ](https://github.com/gusmanb/logicanalyzer/releases/tag/v2.0.1.0)
