### ISSUE TITLE
Not able to install in manjaro linux using add/remove software (Logo40.png seems to be missing)

### ISSUE THREAD

**Issue by tulio84z** [gusmanb/logicanalyzer#114]
im getting 

install: cannot stat '/var/tmp/pamac-build-myuser/logicanalyzer-git/src/logicanalyzer-git/Software/LogicAnalyzer/LogicAnalyzer/Assets/Logo40.png': No such file or directory
==> ERROR: A failure occurred in package_logicanalyzer-git().
    Aborting...

this is the version im installing using add/remove software in manjaro
![image](https://github.com/gusmanb/logicanalyzer/assets/1010546/1c510991-9eed-402b-88a5-c9023236a8fb)

while checking the repo, i saw that indeed there is no Logo40.png
![image](https://github.com/gusmanb/logicanalyzer/assets/1010546/f0fa6342-d686-4831-b3db-0c58c60d0c3e)

**Comment by gusmanb** [comment]
Sorry, ArchLinux packages are not maintained by me nor are officially supported, you should contact the package owner.

I would recommend to download the latest official build from the releases section.
