### ISSUE TITLE
LogicAnalyzer on Mac M2 needs codesign

### ISSUE THREAD

**Issue by ozarchie** [gusmanb/logicanalyzer#115]
I was unable to start LA on a Mac M2 machine until I added 
`codesign --force --deep -s - ./LogicAnalyzer`
in addition to the xattr and chmod commands as per 
https://github.com/gusmanb/logicanalyzer/wiki/04---LogicAnalyzer-Software
Is this normal?

**Comment by gusmanb** [comment]
Yes, it seems that Apple is forcing more and more devs to pay them in order to make any kind of software to work out of the box and they are blocking each day more possibilities to avoid this.

Apple is just greedy right now.

**Comment by ozarchie** [comment]
Thanks Agustin. Apple do really push the price point.
The Info would be a useful addition to the Wiki.
Cheers John
