### ISSUE TITLE
Connect more devices via COMs

### ISSUE THREAD

**Issue by Mikes-brun** [gusmanb/logicanalyzer#119]
Hello,

i tried run CLCapture with multiple devices connected to COMs, but prg accepted only onde device connected via COM. 
CLCapture.exe capture COM8,COM7 100000000 ...
It is possible? When connections are different (COM and WiFi) yes.

**Comment by gusmanb** [comment]
At the moment CLCapture does not support the multidevice functionality, you must use the GUI to use it.

Cheers.
