### ISSUE TITLE
LevelShifter capacitors details

### ISSUE THREAD

**Issue by mateuszradomski** [gusmanb/logicanalyzer#12]
Hi,

I'm having trouble finding the specific capacitance values for the 12 capacitors on the level shifter.
What should I consider when picking out those when I want to build a level shifter myself.

**Comment by gusmanb** [comment]
Hi!

My mistake, I forgot to add the values to the schematic 🤦 
I will update it this evening.

Those are 100nf ceramic 0603 SMD decoupling capacitors. The value/voltage is not critical, anything from 33nf to 470nf and 6v to 50v will work.

These ones will do the job:

https://www.mouser.com/ProductDetail/Kyocera-AVX/06033G104ZAT2A?qs=sGAEpiMZZMukHu%252BjC5l7YaPgIeG5RhuBXYDOluOXX7Q%3D

https://es.aliexpress.com/item/1005003276189139.html

Cheers!
