### ISSUE TITLE
To small definitions for FgChannelColor

### ISSUE THREAD

**Issue by Mikes-brun** [gusmanb/logicanalyzer#120]
When it read data from two devices (48 channels) generate exception on call context.DrawLine method (line 181) because array of FgChannelColor is defined only for 24 items.
Hotfix (bad): duplicate "public static Color[] FgChannelColors => new Color[]" fields to two times.

**Comment by gusmanb** [comment]
This is already solved in the code but the new version has still not been published. Hope to have enough time next month (too much work in real life :/ ).

Cheers.

**Comment by gusmanb** [comment]
If I recall right this is a test version with that problem corrected.

https://mega.nz/file/rPAFRJ6S#9qa-LDqqxHqw8ppV6v3puSrMToAYdSWzkLvB2dhXwXU
