### ISSUE TITLE
Logic Analyser uses .net 7 that is unsupported. 6 and 8 are supported.

### ISSUE THREAD

**Issue by cdwijs** [gusmanb/logicanalyzer#124]
I had to install .net 7 to be able to compile Logic Analyser * .NET 7 is no longer supported:
![image](https://github.com/user-attachments/assets/e5969e9d-1a3f-4679-ac55-c52c940ef448)

Is there a technical reason why version 8 can't be used?

* https://github.com/gusmanb/logicanalyzer/issues/116

**Comment by gusmanb** [comment]
I need to check if AvaloniaUI has been updated to .net 8.0, also if you check the last release of the project is on May 5, before it ran out of support.

If avalonia has been updated to support .net 8 (most probably yes) I will update the framwework version.

**Comment by miguelagve** [comment]
As far as I can tell, I should be supported
[https://docs.avaloniaui.net/docs/faq#what-versions-of-net-can-i-use](url)

**Comment by gusmanb** [comment]
Next release will come with the latest version of Avalonia and .net 8, I have already updated everything locally :)
