### ISSUE TITLE
Logic Analyzer - Modular libraries for protocol detection

### ISSUE THREAD

**Issue by feroxib** [gusmanb/logicanalyzer#130]
Im pretty much sold on your project with all the capabilities it provides and the future outlook is promising as well.

What i really like about Saleae Logic Analyzer is the "plugin" libraries. The different protocols are so different and many in numbers it would be a huge boost for this project if there would be a standardized "measurement" interface in your logic analyzer. This allows a 3rd party writing a plugin library for a specific protocol. 

I think both you and the community could benefit vastly from this!
maybe theres even the chance to write the interface so it would work with the exact plugins from saleae?

**Comment by gusmanb** [comment]
Next version replaces the current plugin system and integrates the decoders system from Sigrok, any decoder written for it will work here.

![imagen](https://github.com/user-attachments/assets/43cdce92-b82a-4af6-afe3-e1aac0fd7eff)
