### ISSUE TITLE
Headers for PCBs?

### ISSUE THREAD

**Issue by bluegizmo83** [gusmanb/logicanalyzer#14]
Where did you find the 2x15 headers for the PCBs? I can't quite tell from the photos but it looks like the Logic PCB as one 2x15 Female header, and the Level Shifter PCB has one 2x15 Male header and one 2x15 Female header? All headers are Right Angle as well it looks like. I've tried to find these headers on Mouser and a few other sites, but can't find them.

**Comment by gusmanb** [comment]
Hi.

Yes, that's correct, the analyzer uses a female 2x15 horizontal head and the shifter a male and a female. I bought those from AliExpress but they're pretty common.

https://es.aliexpress.com/item/4000081601899.html
https://es.aliexpress.com/item/1005001288367127.html

In mouser with a quick search I find the males:

https://www.mouser.com/ProductDetail/Amphenol-FCI/77318-142LF?qs=chTDxNqvsymAZ97VcrzdBw%3D%3D

And in Newark:

https://www.newark.com/w/c/connectors/pin-headers/prl/results?contact-termination-type=through-hole-right-angle&no-of-contacts=30contacts&no-of-rows=2rows&pitch-spacing=2.54mm&product-range=tsw-series

https://www.newark.com/samtec/ipt1-115-01-l-d-ra/header-2-54mm-though-hole-right/dp/85T5056
