### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by lazaj** [gusmanb/logicanalyzer#140]
Open-source hardware projects are wonderful.
As an electronics and embedded software engineer and retrocomputing restorer, they are an integral part of my work toolkit. However, there’s a challenge: while the manufacturing files (Gerbers, pick & place, BOM) are often available, not everyone has the ability to produce PCBs or solder components. This limits the reach of these projects.

More users mean more feedback, which leads to better products. Based on this observation, I’m offering my services to help broaden access. I propose listing your open-source hardware projects on my Tindie store, ensuring your intellectual property and project licenses are fully respected.

My goal is not to make a profit, but to provide access to people who may lack the tools or expertise to produce open-source hardware projects themselves.

Naturally, this work requires time and money, so I commit to pricing the products at 1.5 X the production cost.

Let me know if you're ok.

**Comment by gusmanb** [comment]
This is an open-source project and there is people already selling it on tindie, so feel free to do as you wish, but beware, I'm working in a new hardware revision so it will be better if you wait until it's released.

Cheers.
