### ISSUE TITLE
Not an issue - Is version 6 available?

### ISSUE THREAD

**Issue by ngmacha** [gusmanb/logicanalyzer#158]
At the end of issue #4 "Sigrok driver" you mention about Version 6.0, however the Releases contains only 5.1 version. Please kindly advise if v6 is already available and how to get it. And thank you Dr Gusman for a great project!

**Comment by gusmanb** [comment]
If you want to test the current V6.0 build you can download a beta from the links in this discussion: https://github.com/gusmanb/logicanalyzer/discussions/148

Cheers.
