### ISSUE TITLE
I have some questions about the integrated PCB I will make

### ISSUE THREAD

**Issue by vihor3** [gusmanb/logicanalyzer#16]
I am trying to integrate rp2040 on PCB to complete a more integrated product.But I have a question. I see that your PCB wiring is treated with equal length, but the IO wiring on the rp2040 development board is not of equal length. Do I need to treat the whole process of equal length when I make an integrated PCB?

**Comment by gusmanb** [comment]
Hi @vihor3 

Well, the ideal is always to match trace lengths, the faster the signal sampling is the more important the trace matching length is, think that trace length can introduce delays, very small, in the order of picoseconds, but as the signal can last less than 10ns at 100Msps a good bunch of picoseconds of delay may cause that a signal that is marginally correct to be sampled incorrectly.

If you publish the device don't esitate to send me a link and I will add it to the documentation :)
