### ISSUE TITLE
Seeking Pico 2 PCB Files

### ISSUE THREAD

**Issue by BusPirateV5** [gusmanb/logicanalyzer#173]
I see multiple people with the boards soldered together, but I cannot find consistancy in a Pico 2 design for the GusmanB 24 channel Logic Analyzer V6.0

Can someone please point me in the right direction so that I do not have to re-create the wheel here?

------------------------------------------------------------------------

### Discussed in https://github.com/gusmanb/logicanalyzer/discussions/157

<div type='discussions-op-text'>

<sup>Originally posted by **JimDrewGH** November  9, 2024</sup>
So, I made a few of the new v6.0 boards (be aware that the gerber data for these boards did NOT include the pin labeling or component IDs in the top silkscreen!).  Now that I have them I can not figure out how to enable using 2 boards together.  My sole purpose for these is to capture 42 channels of data.  Anyone know how this is done and how the boards are synchronized?

![IMG_4965](https://github.com/user-attachments/assets/425c7776-c93d-40b3-a4af-5fe1cd853448)
</div>

**Comment by gusmanb** [comment]
Well, users went to the V6.0 branch that is not published as completed, got gerbers that were under development and produced faulty boards (is not the case of Jim as I'm working with him), so to avoid these problems I have made the gerber/KiCad files non-public until the release is completed.

I expect to make the release public finally at the end of January.
