### ISSUE TITLE
v6 LogicAnalyzer startup issue on Linux ~ proposed solution

### ISSUE THREAD

**Issue by LouDnl** [gusmanb/logicanalyzer#175]
After compiling the new version of LogicAnalyzer I get an error after compile
```shell
Unhandled exception. System.IO.FileNotFoundException: Could not find file '/sys/bus/usb/devices/2-1/serial'.
File name: '/sys/bus/usb/devices/2-1/serial'
```

This is caused specifically this piece of code:
https://github.com/gusmanb/logicanalyzer/blob/20f2566f623fda91cb23fb18cea59f76c745e9cf/Software/LogicAnalyzer/SharedDriver/DeviceDetector.cs#L68-L73

This can be fixed (for me) by swapping the code in the above lines like so:
```csharp
var idVendor = File.ReadAllText(Path.Combine(dir, "idVendor")).Trim();
var idProduct = File.ReadAllText(Path.Combine(dir, "idProduct")).Trim();

if (idVendor != vid || idProduct != pid)
    continue;

string serial = File.ReadAllText(Path.Combine(dir, "serial")).Trim();
```

**Comment by gusmanb** [comment]
Please do NOT compile manually the V6.0, this is a work in progress, use the compiled packages that you can find in the discussions (specifically shared in this folder: https://mega.nz/folder/SGxDHAZL#afLGgQbJAaqOYXjhJBwokQ )
