### ISSUE TITLE
instead the TXU0104PWR

### ISSUE THREAD

**Issue by rechan886** [gusmanb/logicanalyzer#19]
Hi,Can i use the TXB0104 for instead TXU0104PWR .becasue TXB0104is cheaper than that one.

**Comment by gusmanb** [comment]
Unfortunatelly no, if you check the TXU datasheet port A is the input and port B is the output so the board is designed like that, in the TXB A and B are in/out but 5V can only be feeded into port B, so it will not work. 

Of course you could modify the PCB and reverse the IC, it will run at the limit of the IC's specs but it should work.
