### ISSUE TITLE
Option to make windows background solid instead of transparent

### ISSUE THREAD

**Issue by RSDuck** [gusmanb/logicanalyzer#25]
Currently the logic analyzer window is transparent which I personally find distracting and to sometimes result in a bad contrast depending on the order of the windows behind it . It can also be noticably resource intensive.

For this reason I'd much appreciate if it was possible to set the window to be made of solid colors.

**Comment by gusmanb** [comment]
Hi.

Sure, I will add an option to make the window solid. Possibly will have the version ready for this weekend.

Cheers.

**Comment by gusmanb** [comment]
Hi.

I finally changed the background without option for transparency, it works better and it reads better so it has been a no brainer.

The code is already uploaded, in the next release it will be included.

Cheers.

**Comment by RSDuck** [comment]
Thanks!
