### ISSUE TITLE
No readme details of build tool chains/versions required to build code

### ISSUE THREAD

**Issue by revell1** [gusmanb/logicanalyzer#28]
I can find no info about what tool chains are required for both target and host code.

For the target I assume it is the Raspberry PI official CPP SDK.

But unsure what is needed for the Windows app.

An extra section in the readme file, or a separate text document with details would be helpful.

Also what toolchain versions.

**Comment by gusmanb** [comment]
Hi.

The firmware was built with the 1.3.1 Pico-SDK. The applications are a single solution, it's built with Visual Studio 2022, community edition is more than enough.

Cheers.
