### ISSUE TITLE
Show basic error information when capture start fails and make capture requirements more clear

### ISSUE THREAD

**Issue by aaronjamt** [gusmanb/logicanalyzer#41]
Currently, the message is very vague and just says that there was an error. Additionally, the requirements for a successful capture should probably be shown in the README or somewhere more obvious. I had to dig through the source code to realize that the reason it wasn't capturing was because I set pre-samples to zero, thinking that I just wanted to maximize the number of samples after the trigger that it captured. I actually wound up reinstalling the firmware on the Pi Pico, redownloading the application from GitHub, rebooting both my machine and the Pi Pico several times, and was about to run a live linux distro until I saw that it was just because pre-samples has to be at least 2.

**Comment by gusmanb** [comment]
Update with new messages released has been released, and info on the settings added to the main project page.
