### ISSUE TITLE
hope to add analog channels

### ISSUE THREAD

**Issue by Hcreak** [gusmanb/logicanalyzer#54]
Previously I was using analog channels on pulseview as a sample oscilloscope. I would like to continue to get this feature on LogicAnalyzer. Will it be added in the near future?  Thx.

**Comment by gusmanb** [comment]
Hi.

There is the idea to convert the analyzer into an oscilloscope, but the timeframe is unspecified. You can find more info [here](https://github.com/gusmanb/logicanalyzer/discussions/30) and [here](https://github.com/gusmanb/logicanalyzer/discussions/51).

Cheers
