### ISSUE TITLE
Wish

### ISSUE THREAD

**Issue by Kabron287** [gusmanb/logicanalyzer#57]
It'll be very useful to use ADC to measure reference voltage of the level shifter 
and use PWM or external DAC to setup reference voltage directly from the SW.
Or 2bits resistive DAC also do the job.

**Comment by gusmanb** [comment]
The ADC will be fried if the external voltage is higher than 3.3v, and using PWM to power the shifters can cause a lot of troubles. Also, there is no free pin left...

**Comment by Kabron287** [comment]
>> Dividers exists.

**Comment by gusmanb** [comment]
> > The ADC will be fried if the external voltage is higher than 3.3v
> 
> Dividers exists.

Cool! PR's also do exist, this is an open-source project so feel free to design it, implement it, test it, all in a way that doesn't disturbs any of the other functionalities and then do a PR wit the changes, if all works I will incorporate it to the design.
