### ISSUE TITLE
Daisy chaining RP2040 Zero

### ISSUE THREAD

**Issue by unreal4me** [gusmanb/logicanalyzer#77]
Hi there, it's a bit unclear what pins one would use to daisy chain RP2040 ZERO.
Thank you and good health!

**Comment by gusmanb** [comment]
Hi.

If you use the provided PCBs there are explicit connectors for this funcion:

![imagen](https://github.com/gusmanb/logicanalyzer/assets/4086913/addb02a5-e88b-4012-82f7-f295526e8c32)

In case that you want to use the device without any pcb you must interconnect GP0/1 (the ones that are shorted) to the chain, basically all the devices must have GP0/1 tied together. GP0 in normal mode is used by the trigger state machine and GP1 is used by the capture, it is how the machines are intercomunicated, so when you tie all these together and enable the multi-device mode the master device sets high GP0 and all the devices included itself receive the signal through GP1 (all the slave devices set GP0 as High-Z).

![imagen](https://github.com/gusmanb/logicanalyzer/assets/4086913/5b13fa3f-11df-405a-ae29-3e9b500e5c31)

Cheers.
