### ISSUE TITLE
Inconsistency in channel naming

### ISSUE THREAD

**Issue by hei5enbrg** [gusmanb/logicanalyzer#8]
The first channel is called "Channel 1" in most of the places in the Logic Analyzer application. In the information box on the right bottom it is indicated as Channel 0. 
![logic_analyzer](https://user-images.githubusercontent.com/7108285/178042468-581e98e0-f6d3-4a0c-b3ba-e96018cd3c96.png)

**Comment by gusmanb** [comment]
Thanks for the report.

It has been corrected and will be available in the next release.

Cheers.
