### ISSUE TITLE
10bit I2C Parsing does not work 

### ISSUE THREAD

**Issue by shawnferry** [gusmanb/logicanalyzer#86]
The mask for 10bit I2C was incorrect resulting in no detection of addresses (fix in #85)

10bit read is not recognized ([implementation based on](https://www.i2c-bus.org/addressing/10-bit-addressing/) 

(Image is from locally running copy of #85)
![image](https://github.com/gusmanb/logicanalyzer/assets/485104/ca78a50b-4944-4526-96c7-3b3eb9a6c4c7)

**Comment by shawnferry** [comment]
This is a 10bit I2C implementation I am working on. I *think* it is correct sample above is from this file. 
[tenbit_sample.csv](https://github.com/gusmanb/logicanalyzer/files/12877117/tenbit_sample.csv)

**Comment by gusmanb** [comment]
I will test it this weekend and will try to publish a new version that includes also the fixes for the folder name of the analyzers and the name of the channels in the dropdowns.

Cheers.
