### ISSUE TITLE
QOL I2C start/stop/repeatstart are commonly invisible

### ISSUE THREAD

**Issue by shawnferry** [gusmanb/logicanalyzer#87]
I'm trying not to pack too many things into a single issue.

As in the region highlighted in #86 even fairly low sample display doesn't always show start/repeat start and rarely shows stops.
I think it would be helpful to either always show (or optionally) show start/stop/repeat start as lines on the rendered display.

With colors is fine but possibly also with a simple geometric indicator circle/triangle/square or single letters S/T/R (to allow for color blind users and to differentiate from trigger locations etc)

My rough thought was something like this ![image](https://github.com/gusmanb/logicanalyzer/assets/485104/4c6e3330-968d-4dda-af5a-bfd9a07c61b3)

Unfortunately I don't have any C# experience and it wasn't immediately clear how I could just cram something like that into the parser.

**Comment by gusmanb** [comment]
Ok, I will think something for the next update, I wanted to do a release last week but right now I'm really busy with my job, I hope to have an update in a couple of weeks.

Cheers.

**Comment by shawnferry** [comment]
🎉

**Comment by gusmanb** [comment]
Damn, I closed this incorrectly, still not implemented... sorry :/

**Comment by gusmanb** [comment]
Ok, I think this will solve the problem.

Now the events will be always rendered, if the space is not enough for the text only the text will be hidden, and also, all the events will be shown as colored areas to the sample marker.

![imagen](https://github.com/gusmanb/logicanalyzer/assets/4086913/3d4bb7ff-a394-4b3b-a936-2069de15542f)

I expect to publish the version with this changes next week.

Cheers.
