### ISSUE TITLE
Simple capture only compile issues, using older function calls

### ISSUE THREAD

**Issue by DangerousPrototypes** [gusmanb/logicanalyzer#90]
Compiling without fast or complex triggers has a few issues. I'm not including fast or complex triggers because I only have 8 IO pins.

LogicAnalyzer.c line 232:
`
started = startCaptureSimple(req->frequency, req->preSamples, req->postSamples, (uint8_t*)&req->channels, req->channelCount, req->trigger, req->inverted, req->captureMode);
`
Seems to be an older version of the function. I fixed it by copying the simple capture function from the code above:
`
started = startCaptureSimple(req->frequency, req->preSamples, req->postSamples, req->loopCount, (uint8_t*)&req->channels, req->channelCount, req->trigger, req->inverted, req->captureMode);
`

line 607 has no ifdef to check if fast is included:
`
 check_fast_interrupt();
`

LogicAnalyzer.pio line 373 too:
`
    gpio_deinit(COMPLEX_TRIGGER_OUT_PIN);
    gpio_deinit(COMPLEX_TRIGGER_IN_PIN); 
`

line 595 also:
`
        else if(lastCaptureType == CAPTURE_TYPE_COMPLEX)
            complex_capture_completed();
        else if(lastCaptureType == CAPTURE_TYPE_FAST)
            fast_capture_completed();
`

the pinMap[] around 203: I found I could just remove the COMPLEX_TRIGGER_IN_PIN for simple only mode:

`
//const uint8_t pinMap[] = {2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,26,27,28,COMPLEX_TRIGGER_IN_PIN};  
const uint8_t pinMap[] = {2,3,4,5,6,7,8,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9};  
`

There's a couple other issues, I'll document them as I find them.

Great firmware, thank you for your work on this!

**Comment by gusmanb** [comment]
Thanks for the report, I have corrected the bugs when disabling the complex trigger support. I will upload the changes next week as it's in a new firmware that also changes transfer bulks and I'm testing it.

Cheers.
