### ISSUE TITLE
Improve on the hardcoded PICO_SDK_PATH in Firmware/LogicAnalyzer CMakeLists.txt

### ISSUE THREAD

**Issue by Ragebone** [gusmanb/logicanalyzer#94]
Hello,
current version in the master hardcodes the SDK path, link here:
https://github.com/gusmanb/logicanalyzer/blob/6ab103e120eba0f76b678651ea4dabeb6a76e063/Firmware/LogicAnalyzer/CMakeLists.txt#L10

The included `pico_sdk_import.cmake` can handle taking `PICO_SDK_PATH` from the environment but won't because it is already defined.

Please excuse me asking like this, is it possible for you to use the environment variable for setting the SDK-Path instead? 

Thank you.
Sincerely
Norman

**Comment by gusmanb** [comment]
Removed hardcoded define from CMakeLists.txt
