### ISSUE TITLE
Measure Window Blank

### ISSUE THREAD

**Issue by tibohu** [gusmanb/logicanalyzer#95]
Dear Gusmanb,
there is a strange behaviour. The popup Measure Window became blank, it worked perfectly before.
Even stranger: I deleted the full app folder "LogicAnalyzer-5.0.0.0-win-x64". Unzipped the untouched download zip file again. Started the LogicAnalyzer again but Measure still not working as expected.
![GusmLA Error_MeasureBlank](https://github.com/gusmanb/logicanalyzer/assets/26720708/8cf9babb-5779-4b28-b891-b817b168b1e4)

**Comment by gusmanb** [comment]
Hi.

Did you changed your monitor or had another one connected and now you removed it?

In any case, the settings are not stored in the application folder, they go at %appdata%\LogicAnalyzer (usually "C:\Users\(your user)\AppData\Roaming\LogicAnalyzer" on Windows, "home/.config/LogicAnalyzer" on Linux), delete the AppConfig.json and that should reset all the layout settings.

Cheers.

**Comment by tibohu** [comment]
Thank you!
Deleting the AppConfig.json file solved the problem.
Regarding your question, I did not change or connect to another monitor.

by the way, it would be nice if we
-could change the color of the channels
-keep the last setting in the windows
(should I place these into a newer thread?)

**Comment by gusmanb** [comment]
Channel colors can now be selected and are preserved in stored captures.

Will be included in the next release.

![imagen](https://github.com/gusmanb/logicanalyzer/assets/4086913/ff7e9c24-5309-4af4-addd-0a02f469cd5d)
